import IMAGES from './imagePath';

export const categoryData = [
  {
    id: '1',
    name: '21WN',
    price: 120,
    image: IMAGES.CATERGORY_1,
    category: 'gents',
    description: 'reversible angora cardigan',
  },
  {
    id: '2',
    name: 'lame',
    price: 120,
    image: IMAGES.CATERGORY_2,
    category: 'gents',
    description: 'reversible angora cardigan',
  },
  {
    id: '3',
    name: '21WN',
    price: 120,
    image: IMAGES.CATERGORY_3,
    category: 'gents',
    description: 'reversible angora cardigan',
  },
  {
    id: '4',
    name: 'lame',
    price: 120,
    image: IMAGES.CATERGORY_4,
    category: 'gents',
    description: 'reversible angora cardigan',
  },
  {
    id: '5',
    name: '21WN',
    price: 120,
    image: IMAGES.CATERGORY_5,
    category: 'gents',
    description: 'reversible angora cardigan',
  },
  {
    id: '6',
    name: 'lame',
    price: 120,
    image: IMAGES.CATERGORY_6,
    category: 'gents',
    description: 'reversible angora cardigan',
  },
  {
    id: '7',
    name: '21WN',
    price: 120,
    image: IMAGES.CATERGORY_7,
    category: 'gents',
    description: 'reversible angora cardigan',
  },
  {
    id: '8',
    name: 'lame',
    price: 120,
    image: IMAGES.CATERGORY_8,
    category: 'gents',
    description: 'reversible angora cardigan',
  },
  {
    id: '9',
    name: 'lame',
    price: 120,
    image: IMAGES.CATERGORY_4,
    category: 'gents',
    description: 'reversible angora cardigan',
  },
  {
    id: '10',
    name: '21WN',
    price: 120,
    image: IMAGES.CATERGORY_5,
    category: 'gents',
    description: 'reversible angora cardigan',
  },
];
